### ISSUE TITLE
Consider bumping MSRV 

### ISSUE THREAD

**Issue by jbesraa** [payjoin/rust-payjoin#114]
there is a short discussion here https://github.com/lightningdevkit/rust-lightning/pull/2681
as @notmandatory mentions and as we seen and the last few PRs, it becomes a pain to maintain the 1.57 and it looks like the ecosystem is moving toward 1.63.

**Comment by DanGould** [comment]
Sounds good to me. It would be awesome to migrate `payjoin-cli` to match msrv too by including `minreq` so we can set a good example for downstream integrations

**Comment by DanGould** [comment]
closed by #115, and payjoin-cli by #119
