### ISSUE TITLE
Upgrade `rust-bitcoin` to `0.32`

### ISSUE THREAD

**Issue by jbesraa** [payjoin/rust-payjoin#124]

**Comment by jbesraa** [comment]
started this https://github.com/Kixunil/bip21/pull/19
will upgrade on our side when the above is merged

**Comment by DanGould** [comment]
Our dependencies tend to use BDK so far, so they're stuck on rust-bitcoin 0.29.x. I hope they start updating more frequently as BDK 1.0 comes out.

**Comment by oleonardolima** [comment]
> Our dependencies tend to use BDK so far, so they're stuck on rust-bitcoin 0.29.x. I hope they start updating more frequently as BDK 1.0 comes out.

I was taking a look a #127, and in BDK we are at 0.32 now on [v1.0.0-alpha.13](https://github.com/bitcoindevkit/bdk/releases/tag/v1.0.0-alpha.13).

Is it better to upgrade to 0.31 first or directly to 0.32 ?

**Comment by DanGould** [comment]
Until psbt-v2 (https://crates.io/crates/psbt-v2/0.1.1/dependencies) updates to 0.32, 0.31 is probably the best.
