### ISSUE TITLE
Fix failing doc tests

### ISSUE THREAD

**Issue by jbesraa** [payjoin/rust-payjoin#137]
when running `cargo test` locally a good amount of doc tests are failing
![Screenshot from 2023-12-13 16-43-53](https://github.com/payjoin/rust-payjoin/assets/21229375/db23a734-e313-40fb-a2e5-16a5dc582ffc)

**Comment by DanGould** [comment]
It would be great to replace what are currently the top tests with a payjoindevkit.org tutorial tagged to a certain release. perhaps 0.11.0, the last Payjoin v1 only release

**Comment by DanGould** [comment]
https://github.com/payjoin/rust-payjoin/issues/89

**Comment by DanGould** [comment]
Removed with #179, superseded by #89 and #180
