### ISSUE TITLE
Create scripts to run local checks

### ISSUE THREAD

**Issue by jbesraa** [payjoin/rust-payjoin#145]
currently its a bit of work to run all of the tests localy(integartion, v2 and other features), it would be nice to have a single script, 
maybe 'ci-test' that we can run locally before pushing code, and we can use the same script in ci

**Comment by DanGould** [comment]
agree, this is a high leverage housekeeping issue especially since some of our dev-deps aren't msrv at the moment.

**Comment by DanGould** [comment]
Changed title since we'd found it'd also be nice to have [a script to check each commit builds](https://github.com/lightningdevkit/rust-lightning/blob/main/ci/check-each-commit.sh)

**Comment by DanGould** [comment]
For the time being I tested that running [`act`](https://github.com/nektos/act) runs the tests as they would in CI from the yaml files

**Comment by DanGould** [comment]
Seems like [`just`](https://github.com/casey/just) recipes are also a great option here that related projects are already making good use of
