### ISSUE TITLE
 Implementation of #[derive(Clone)] on Multiple Structs to Facilitate uniffi Bindings

### ISSUE THREAD

**Issue by BitcoinZavior** [payjoin/rust-payjoin#164]
Limitations due to inability to clone certain struct instances. This is an issue when attempting to create bindings using the [uniffi-rs](https://github.com/mozilla/uniffi-rs) crate. Uniffi is being used for generating foreign-function interfaces in Rust which are used fo creating bindings for different platforms, mainly Python, Kotlin and Swift. To resolve this issue #[derive(Clone)] attribute for following structs should be implemented.

- Configuration
- PrjUriRequest
- Context
- MaybeInputsOwned
- MaybeMixedInputScripts
- MaybeInputsSeen
- OutputsUnknown
- ProvisionalProposal
- PayjoinProposal

Adding Clone to the structs will make the FFI code simpler, ref: https://github.com/LtbLightning/payjoin-ffi. Right now, most structs have just one function. When you call this function, it takes over the memory because it uses self and not &self. This works fine in Rust, but it's a problem for FFI where we need to use &self.

Without Clone, we can't call payjoin functions directly. We've been using mutexes and extra helper functions to get around this. If we implement Clone, we can copy structs when we need to, making the FFI code cleaner and easier to work with. This change will help avoid those extra workarounds thereby making the code easier to maintain and enhance.

**Comment by DanGould** [comment]
Not only are common traits like `Clone` important for ffi but also [for API interoperability in genera](https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits) . Assigned @BitcoinZavior per our discussion on Discord
