### ISSUE TITLE
Serialization and Deserialization of V2Context Object for Rust Payjoin UniFFI Wrapper

### ISSUE THREAD

**Issue by BitcoinZavior** [payjoin/rust-payjoin#175]
As ClientResponse in OHTTP cannot implement clone as per https://github.com/martinthomson/ohttp/issues/60
creating a Uniffi wrapper for Rust Payjoin will require serialisation and deserialisation of V2Context object.

Would be great to have a solution for this.

Without ClientResponse implementing clone some Possible options are:

- Expose Selected V2Context Struct Values:
One option is to selectively expose specific values within the V2Context struct as public, making them accessible for serialization and deserialization in our FFI code. This approach allows us to work around the limitations posed by the ClientResponse clone implementation.

- Implement Serialization and Deserialization for V2Context:
Implement the Serialize and Deserialize traits for the V2Context struct. By doing so, we can directly serialize and deserialize V2Context objects without needing to expose individual values.

- Create Helper Functions:
Another option is to create helper functions within the Rust Payjoin library that expose the required values, such as the relay parameter and other relevant data. These functions would enable data transfer and manipulation between the Rust Payjoin library and the UniFFI wrapper.

**Comment by DanGould** [comment]
Can you explain in detail why UniFFI requires `V2Context` to be `Clone`?

**Comment by DanGould** [comment]
This suggestion is making the most sense of those proposed so far. Could this change be done inside `payjoin-ffi` or would we need to address it in `payjoin`? It sounds like the latter.

> The problem is that we cannot use a struct [defined in] another [crate] directly in our [UniFFI] wrapper struct, without wrapping [the foreign struct] in a reference [counter] (Arc)

Is my understanding here correct? I'm not sure I understand the following phrase

> because we will not be able to [own] the ClientResponse [data] from the Arc.

Why does the wrapper need to own ClientResponse, if I'm even understanding the limitation correctly?

**Comment by BitcoinZavior** [comment]
> This suggestion is making the most sense of those proposed so far. Could this change be done inside `payjoin-ffi` or would we need to address it in `payjoin`? It sounds like the latter.
> 
Thats right, rust payjoin will not require any change, payjoin-ffi will address this by creating a wrapper struct called `ClientResponse` that has a variable of type `Mutex<Option<ClientResponse>>`

**Comment by DanGould** [comment]
Ah I misunderstood. If this can be solved in payjoin-ffi, is this issue closed in rust-payjoin?

**Comment by DanGould** [comment]
Seems to be able to be solved in payjoin-ffi
