### ISSUE TITLE
Prevent `send::RequestContext::extract_v1` to take owner of `self`

### ISSUE THREAD

**Issue by jbesraa** [payjoin/rust-payjoin#183]
`extract_v1` signature takes full ownership of self 
```pub fn extract_v1(self) -> Result<(Request, ContextV1), CreateRequestError> {```

This is tricky if we want to use it in the same scope with other functions that consume self, specifically in my case
I need to invoke it after invoking `extract_v2` in the same function scope, while `extract_v2` takes a reference self, `extract_v1` takes full owner ship.

**Comment by DanGould** [comment]
Seems like this makes cloning the default rather than exception.

What if, where we run into ownership issues, we call `req_ctx.clone().extract_v1()` so that it's clone is only done in exceptional cases?

**Comment by jbesraa** [comment]
As `send::RequextContext` implements `clone`, we dont need this any more.
