### ISSUE TITLE
Downstream users must manually set headers

### ISSUE THREAD

**Issue by DanGould** [payjoin/rust-payjoin#224]
`Request` does not include required "Content-Type" headers 

- `Content-Type: text/plain` for v1 send requests
- `Content-Type: message/ohttp-req` for v2 requests

We also have 2 separate `Request` structs that should be made into one.

Either the `Request` struct should have a `pub headers: HashMap<String, String>` field, which would need to be iterated over, or a `pub content_type: String` field which could be accessed directly. If the latter option is chosen, it simplifies the downstream implementation but could cause a problem if another header type became required to send `Request` data via http clients in the future. I don't think that is going to happen so I'm inclined to go with the latter for v1 & v2 payjoin but I'm open to hearing opinions.

v1 requests do also require a `Content-Length` header (and maybe v2 should as well?), but all of the http clients I've encountered set that automatically.

@Kixunil any reason you didn't include content_type or headers fields in the original `Request` implementation? I see that you did leave Request #[non_exhaustive].

**Comment by Kixunil** [comment]
I'm not sure but I think I didn't want to make assumptions about HTTP clients and their API.
