### ISSUE TITLE
Add `--version, -v` option `payjoin-cli`

### ISSUE THREAD

**Issue by thebrandonlucas** [payjoin/rust-payjoin#255]
It would be nice if we could do `payjoin-cli --version` or `payjoin-cli -v` so that we can always tell if we're on the correct version. We could use these in tutorials to remove ambiguity and eliminate one potential source of confusion

**Comment by DanGould** [comment]
This should be straightforward to implement

https://chatgpt.com/share/006a9860-66fa-44a8-a83a-9d43cbbc6b93

**Comment by DanGould** [comment]
fixed by #262
