### ISSUE TITLE
Building fail with `v2, send` features @ v0.15

### ISSUE THREAD

**Issue by jbesraa** [payjoin/rust-payjoin#258]
I was not able to reproduce this in `rust-payjoin` while building it locally but in pr https://github.com/lightningdevkit/ldk-node/pull/295/checks iam not able to only include `v2, send`, it throws the following error
![Screenshot from 2024-05-21 10-12-34](https://github.com/payjoin/rust-payjoin/assets/21229375/b81d41f4-6230-4afe-aca2-b3544b8663c2)

`rand` is re-exported with `receive` feature so adding the `receive` would make it compile.

**Comment by DanGould** [comment]
The link you shared goes only to the most recent checks on https://github.com/lightningdevkit/ldk-node/pull/295. May you please share the exact check that fails?

**Comment by DanGould** [comment]
Do the changes in #261 fix your issue?

**Comment by jbesraa** [comment]
> The link you shared goes only to the most recent checks on [lightningdevkit/ldk-node#295](https://github.com/lightningdevkit/ldk-node/pull/295). May you please share the exact check that fails?

I didnt push the code without the `receive` feature as it failed to compile, to reproduce it locally you can remove the `receive` in this commit  https://github.com/lightningdevkit/ldk-node/pull/295/commits/532c6ef72b0471a1808b71c07f97a3ca8fe658b4 and try to build.

#261 solved the problem. Thanks.

**Comment by jbesraa** [comment]
If you have the time, I would appreciate your input on the PR https://github.com/lightningdevkit/ldk-node/pull/295(not able to tag you in the pr for some reason). It adds a payjoin sender implementation to ldk node.
