### ISSUE TITLE
Is it possible to "expect all UTXO data to be filled in" for v2 payjoin and NOT v1

### ISSUE THREAD

**Issue by DanGould** [payjoin/rust-payjoin#359]
The version 1 spec requied UTXO data to be cleared on the transport message layer instead of by the sender's typestate machine. Can we accomodate this, or does it make more sense to leave it completely backwards compatible with the v1 spec.

I've left a [detailed fix proposal in the bips repo](https://github.com/bitcoin/bips/pull/1396), which seems to have consensus, but the BIP 78 author's time is limited and it would be difficult to deploy the change in the production payjoin v1 implementations

**Comment by spacebear21** [comment]
IMO makes more sense to stay backwards compatible and not add unnecessary complexity for no great gain.
