### ISSUE TITLE
crates.io `bitcoin-ohttp` repo URL is wrong

### ISSUE THREAD

**Issue by notmandatory** [payjoin/rust-payjoin#378]
On crates.io the repo URL for [bitcoin-ohttp](https://crates.io/crates/bitcoin-ohttp) is set to https://crates.io/crates/bitcoin-ohttp but looks like it should be https://github.com/payjoin/ohttp/tree/main/ohttp.  @DanGould is the owner on crates.io so he'll need to fix it.

**Comment by DanGould** [comment]
Thanks for the suggestion @notmandatory. I made [a PR](https://github.com/payjoin/ohttp/pull/2), and used https://github.com/payjoin/ohttp. Any reason to point directly to the main branch?
