### ISSUE TITLE
Allow recipeint to contribute fee if receiver sets their own minfeerate

### ISSUE THREAD

**Issue by DanGould** [payjoin/rust-payjoin#41]
Now even if a minfeerate is specified by the client the receiver never contributes fees

This is especially critical if the sender's maxadditionalfeecontribution is less than the amount to maintain feerate, either if they don't have enough sats (unlikely) or the receiver wants to add more inputs and outputs to batch transactions

**Comment by jbesraa** [comment]
Is this still needed? happy to pick it up if so.

**Comment by spacebear21** [comment]
Closed by https://github.com/payjoin/rust-payjoin/pull/332
