### ISSUE TITLE
Expose Interface for FFI

### ISSUE THREAD

**Issue by DanGould** [payjoin/rust-payjoin#44]
pure functions which take bytes as arguments and return bytes are simple to bind to. Right now we use rust typestate which is easy to reason about but hard to bind to. Perhaps static functions could be exposed as a feature, and the typestate could be built off of the static functions to make this library easy to consume downstream.

---
The BDK approach to FFI is documented here https://hackmd.io/@bdk/bindings-everywhere

After talking to @thunderbiscuit, it sounds like UniFFI handles callback interfaces without too much problem. They don't *necessarily* need to be static. The biggest bindings want with that approach is to support WASM bindings (like [this example](https://github.com/danielabrozzoni/bdk-nodejs)) in combination with the [bitcoin-frontier](https://github.com/thunderbiscuit/bitcoin-frontier) demonstratedg mobile/python UniFFI bindings.

see: https://github.com/LtbLightning/payjoin-ffi/issues/1

**Comment by DanGould** [comment]
@kixunil had a comment on this topic over email

> Are you doing FFI within the same crate? Cause I think it's better to have a separate wrapper crate for that so that pure rust code doesn't need to pull in C compiler and other garbage.

This idea sounds right to me. Plainly I'm not sure what the best way to go about this is because I have not exposed rust via FFI before.

**Comment by Kixunil** [comment]
My last project actually had WASM bindings so I have a fresh experience. :)

What I ended up doing is to wrap the types used by the internal Rust library in a higher-level API that is easier to use from JS. E.g:


```rust
#[wasm_bindgen]
pub struct Invoice(bip21::Uri /* checked, no extras */);

#[wasm_bindgen]
impl Invoice {
    pub fn link(&self) -> String {
        self.0.to_string()
    }

    pub fn qr_code_data(&self) -> String {
        format!("{:#}", self.0)
    }
}
```

**Comment by thunderbiscuit** [comment]
I agree with the sentiment that binding should live in separate repositories. There is a fair amount of wrapping that often needs to take place no matter what technique/tool is used. Easier to treat the Rust library as an internal implementation detail of the bindings lib.

**Comment by DanGould** [comment]
@BitcoinZavior now that https://github.com/LtbLightning/payjoin-ffi exists, is this issue closed?
