### ISSUE TITLE
Add `PjUri` builder

### ISSUE THREAD

**Issue by DanGould** [payjoin/rust-payjoin#62]
There's no easy way to construct a pj bip21 uri without creating a string. This leads to very ugly construction

```rs
    fn handle_get_bip21(&self, amount: Option<Amount>) -> Response {
        let address = self.bitcoind.get_new_address(None, None).unwrap();
        let uri_string = if let Some(amount) = amount {
            format!(
                "{}?amount={}&pj={}",
                address.to_qr_uri(),
                amount.to_btc(),
                self.config.pj_endpoint
            )
        } else {
            format!("{}?pj={}", address.to_qr_uri(), self.config.pj_endpoint)
        };
        // TODO handle errors
        let uri = payjoin::Uri::try_from(uri_string.clone()).unwrap();
        let _ = uri.check_pj_supported().unwrap();
        Response::text(uri_string)
    }
```

More ergonomic interface might look like

```rs
let  pj_uri = PjUriBuilder::new(address, pj_endpoint).amount(amount).build();
```

Consider whether the base bip21 library can introduce a builder pattern.

**Comment by jbesraa** [comment]
@DanGould happy to pick this up

**Comment by DanGould** [comment]
great! Any changes may lend themselves to the  `bip21` crate too https://github.com/Kixunil/bip21, just something to be aware of.

**Comment by jbesraa** [comment]
so will start discussion here before I create a PR

- the commented code in `build` is something we would need to add also I guess, and thats where the string manipulation will happen?
-  what do u think about the supertrait and using 'static in the struct, are these following the correct approach?

```rust
pub trait AnyNetworkValidation: bitcoin::address::NetworkValidation {}

struct PjUriBuilder {
    address: bitcoin::Address,
    pj_endpoint: &'static str,
    amount: Option<Amount>,
}

impl PjUriBuilder {
    fn new(address: bitcoin::Address, pj_endpoint: &'static str) -> Self {
        Self { address, pj_endpoint, amount: None }
    }

    fn amount(mut self, amount: Amount) -> Self {
        self.amount = Some(amount);
        self
    }

    fn build<'b, N: AnyNetworkValidation>(self) -> payjoin::Uri<'b, N> {
        // let mut uri = payjoin::Uri::builder(self.address, self.pj_endpoint);
        // if let Some(amount) = self.amount {
        //     uri = uri.amount(amount);
        // }
        // uri.build()
    }
}

```

**Comment by DanGould** [comment]
I think this thinking is right and it might make sense to only pass validated addresses to new, and valid url::Url to pj_endpoint (or at least do that validation inside new and otherwise return an error). valid pj endpoints are either https:// or .onion.

**Comment by DanGould** [comment]
This may also be an opportunity to contribute the builder pattern in https://github.com/Kixunil/bip21. Might be worth opening a PR at the same time to benefit from the skilled reviewers there too
