### ISSUE TITLE
Allow replacing output and inserting new outputs

### ISSUE THREAD

**Issue by Kixunil** [payjoin/rust-payjoin#69]
This is needed for fancy things like batching or efficient LN channel opening...

**Comment by DanGould** [comment]
This is supported in [`PayjoinProposal`](https://github.com/payjoin/rust-payjoin/blob/45f6c2b4c976fe5a1bd253c14bea3ada59aefa36/payjoin/src/receive/mod.rs#L381-L452). What do you have in mind that is not yet possible?

**Comment by Kixunil** [comment]
Those handle add inputs, not outputs. I missed `substitute_output_address` but it really should be `substitute_script_pubkey` to allow LN channels. Also it'd be great to have methods to reasonably modify values - e.g. giving a discount to the payer.

**Comment by jbesraa** [comment]
Added this https://github.com/payjoin/rust-payjoin/pull/233/commits/ef8c7ec53675d06d29aa479456d2b2d812fc7402

**Comment by DanGould** [comment]
closed by #313
