### ISSUE TITLE
Refactor `try_preserving_privacy` for correctness and flexibility

### ISSUE THREAD

**Issue by Kixunil** [payjoin/rust-payjoin#70]
> **Original Title**: *`try_preserving_privacy` should take something more flexible than `HashMap`*

Some people might want to use a database or a different data structure. The type should be something like `impl IntoIterator + Index<OutPoint>`

**Comment by DanGould** [comment]
Since mixed input types aren't allowed in BIP 78 It should alto filter candidate inputs by sender input type

**Comment by DanGould** [comment]
It seems like the `Index` is used for in-memory data structures, not databases, and at least for now, our try_preserving_privacy implementation only needed to iterate. So the solution was just to use `impl IntoIterator<(Amount, OutPoint)>`
