### ISSUE TITLE
Refactor `Request` to include named `context` field

### ISSUE THREAD

**Issue by DanGould** [payjoin/rust-payjoin#80]
~Request.uri and Request.body still need to be marshaled into an http library's client. In working through the issue with a dev, I think it would be more ergonomic to just return `(uri: Uri, body: Vec<u8>)`~

After seeing the tuple solution in practice, I think it would make more sense to name context as a field in `Request` and have `create_pj_request` return `Request` instead of `(Request, Context)`. tuples are not as intuitive since they lack the documentation in the form of a name or a docstring

**Comment by jbesraa** [comment]
started this branch:

https://github.com/jbesraa/rust-payjoin/commit/5230852e5ee8b970ce429e26c464bc3f806f2668
